
import React from 'react';

const AlertIcon: React.FC<{className?: string}> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
        <circle cx="12" cy="12" r="10"></circle>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12.01" y2="16"></line>
    </svg>
);

const Disclaimer: React.FC = () => {
  return (
    <div className="mt-8 bg-amber-100 border-l-4 border-amber-500 text-amber-800 p-4 rounded-r-lg" role="alert">
      <div className="flex">
        <div className="py-1">
          <AlertIcon className="h-6 w-6 text-amber-500 mr-4"/>
        </div>
        <div>
          <p className="font-bold">Important Disclaimer</p>
          <p className="text-sm">
            This analysis is generated by an artificial intelligence and is intended for informational purposes only. It is not a medical diagnosis. Please consult with a qualified healthcare professional for an accurate diagnosis and treatment plan. Do not disregard or delay seeking professional medical advice based on this report.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
